/* =========================================================
 * 人物关系数据（a, b 为 PEOPLE 中的 id，t 为关系描述）
 * ========================================================= */

const RELATIONS = [
  /* 晚清与对外战争 */
  { a: "daoguang",     b: "linzexu",      t: "君臣 · 授命禁烟" },
  { a: "daoguang",     b: "qishan",       t: "君臣" },
  { a: "linzexu",      b: "guantianpei",  t: "同守虎门海防" },
  { a: "linzexu",      b: "qishan",       t: "主战与主和之争" },
  { a: "senggelinqin", b: "yixin",        t: "同僚 · 御侮议和" },
  { a: "yixin",        b: "cixi",         t: "叔嫂 · 辛酉政变" },
  { a: "cixi",         b: "guangxu",      t: "姨甥 · 垂帘掣肘" },
  { a: "dingruchang",  b: "dengshichang", t: "提督与管带" },
  { a: "dingruchang",  b: "lihongzhang",  t: "上下级" },
  { a: "lihongzhang",  b: "yitengbowen",  t: "马关谈判对手" },
  { a: "fengzicai",    b: "lihongzhang",  t: "一主战一主和" },

  /* 太平天国与湘淮军 */
  { a: "hongxiuquan",  b: "yangxiuqing",  t: "天王与东王" },
  { a: "hongxiuquan",  b: "shidakai",     t: "天王与翼王" },
  { a: "yangxiuqing",  b: "shidakai",     t: "同僚 · 天京事变" },
  { a: "zengguofan",   b: "hongxiuquan",  t: "生死对手" },
  { a: "zengguofan",   b: "lihongzhang",  t: "师生 · 幕府历练" },
  { a: "zengguofan",   b: "zuozongtang",  t: "湘军同袍" },
  { a: "lihongzhang",  b: "zuozongtang",  t: "海防塞防之争" },
  { a: "lihongzhang",  b: "zhangzhidong", t: "洋务同道" },
  { a: "yixin",        b: "zengguofan",   t: "洋务同盟" },
  { a: "lihongzhang",  b: "cixi",         t: "倚重之臣" },

  /* 维新变法 */
  { a: "guangxu",      b: "kangyouwei",   t: "君臣 · 锐意变法" },
  { a: "kangyouwei",   b: "liangqichao",  t: "师生 · 康梁" },
  { a: "kangyouwei",   b: "tansitong",    t: "变法同志" },
  { a: "liangqichao",  b: "tansitong",    t: "挚友" },
  { a: "cixi",         b: "kangyouwei",   t: "政变追杀" },
  { a: "yuanshikai",   b: "guangxu",      t: "告密出卖" },

  /* 辛亥与民初 */
  { a: "sunzhongshan", b: "huangxing",    t: "并称“孙黄”" },
  { a: "sunzhongshan", b: "songjiaoren",  t: "革命同志" },
  { a: "sunzhongshan", b: "yuanshikai",   t: "让位与窃国" },
  { a: "songjiaoren",  b: "yuanshikai",   t: "刺宋案" },
  { a: "huangxing",    b: "liyuanhong",   t: "武昌起义" },
  { a: "liangqichao",  b: "cai'e",        t: "师生 · 护国密谋" },
  { a: "cai'e",        b: "yuanshikai",   t: "护国讨袁" },
  { a: "sunzhongshan", b: "jiangjieshi",  t: "知遇提携" },
  { a: "sunzhongshan", b: "wangjingwei",  t: "领袖与幕僚" },
  { a: "xuxilin",      b: "qiujin",       t: "皖浙同谋" },
  { a: "yuanshikai",   b: "cixi",         t: "宠臣" },

  /* 北洋军阀 */
  { a: "yuanshikai",   b: "duanqirui",    t: "北洋上下级" },
  { a: "liyuanhong",   b: "duanqirui",    t: "府院之争" },
  { a: "liyuanhong",   b: "zhangxun",     t: "引狼入室" },
  { a: "duanqirui",    b: "zhangxun",     t: "马厂誓师讨逆" },
  { a: "wupeifu",      b: "zhangzuolin",  t: "直奉大战" },
  { a: "wupeifu",      b: "sun_chuanfang",t: "直系同源" },
  { a: "sun_chuanfang",b: "jiangjieshi",  t: "北伐对手" },
  { a: "zhangzuolin",  b: "zhangxueliang",t: "父子" },
  { a: "zhangxueliang",b: "jiangjieshi",  t: "易帜归顺 · 兵谏" },
  { a: "zhangxueliang",b: "yanghucheng",  t: "西安事变搭档" },
  { a: "zhangxueliang",b: "zhouenlai",    t: "西安斡旋" },
  { a: "fengyuxiang",  b: "jiangjieshi",  t: "结拜兄弟 · 数度反目" },

  /* 国民党 · 抗战 */
  { a: "lizongren",    b: "baichongxi",   t: "桂系搭档" },
  { a: "lizongren",    b: "jiangjieshi",  t: "亦盟亦敌" },
  { a: "baichongxi",   b: "jiangjieshi",  t: "貌合神离" },
  { a: "lizongren",    b: "zhangzizhong", t: "台儿庄并肩" },
  { a: "jiangjieshi",  b: "wangjingwei",  t: "政敌 · 宁汉合流" },
  { a: "jiangjieshi",  b: "tangshengzhi", t: "南京守卫" },
  { a: "jiangjieshi",  b: "xiejinyuan",   t: "上下级" },
  { a: "jiangjieshi",  b: "xueyue",       t: "上下级" },
  { a: "jiangjieshi",  b: "wei_lihuang",  t: "上下级" },
  { a: "jiangjieshi",  b: "du_yuming",    t: "救火大将" },
  { a: "jiangjieshi",  b: "fuzuoyi",      t: "上下级" },
  { a: "tonglinge",    b: "zhaodengyu",   t: "南苑并肩殉国" },
  { a: "xueyue",       b: "gangcunNingci",t: "长沙会战对手" },
  { a: "gangcunNingci",b: "jiangjieshi",  t: "受降" },
  { a: "du_yuming",    b: "wei_lihuang",  t: "辽沈同僚" },

  /* 新文化与中共 */
  { a: "chenduxiu",    b: "lidazhao",     t: "南陈北李 · 相约建党" },
  { a: "chenduxiu",    b: "caiyuanpei",   t: "北大同仁" },
  { a: "chenduxiu",    b: "maozedong",    t: "革命引路人" },
  { a: "caiyuanpei",   b: "hushi",        t: "校长与教授" },
  { a: "luxun",        b: "hushi",        t: "新文化同侪" },
  { a: "luxun",        b: "caiyuanpei",   t: "故交知遇" },
  { a: "maozedong",    b: "zhouenlai",    t: "毕生战友" },
  { a: "maozedong",    b: "zhu_de",       t: "朱毛红军" },
  { a: "maozedong",    b: "pengdehuai",   t: "上下级" },
  { a: "maozedong",    b: "linbiao",      t: "上下级" },
  { a: "maozedong",    b: "fuzuoyi",      t: "北平和平解放" },
  { a: "zhouenlai",    b: "zhu_de",       t: "入党介绍人" },
  { a: "zhu_de",       b: "pengdehuai",   t: "八路军正副总指挥" },
  { a: "pengdehuai",   b: "zuoquan",      t: "并肩参谋" },
  { a: "linbiao",      b: "nierongzhen",  t: "平型关搭档" },
  { a: "linbiao",      b: "luo_ronghuan", t: "军政搭档" },
  { a: "linbiao",      b: "wei_lihuang",  t: "辽沈对手" },
  { a: "linbiao",      b: "fuzuoyi",      t: "平津对手" },
  { a: "liubocheng",   b: "dengxiaoping", t: "刘邓大军" },
  { a: "liubocheng",   b: "helong",       t: "南昌起义" },
  { a: "zhouenlai",    b: "helong",       t: "南昌起义" },
  { a: "zhouenlai",    b: "yeting",       t: "南昌起义 · 新四军" },
  { a: "chenyi",       b: "suyu",         t: "陈粟搭档" },
  { a: "chenyi",       b: "dengxiaoping", t: "淮海总前委" },
  { a: "liubocheng",   b: "suyu",         t: "淮海并肩" },
  { a: "suyu",         b: "du_yuming",    t: "淮海对手" },
  { a: "chenyi",       b: "yeting",       t: "新四军" }
];
