server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # 协商缓存：保证“检查更新”拉到新版本后浏览器立即获取最新资源
    add_header Cache-Control "no-cache, must-revalidate";

    location / {
        try_files $uri $uri/ /index.html;
    }
}
